## Settings
title: My Insider
owner: "Jayasurya Obbu"
url: "https://mr-circuit.github.io"
baseurl: "/"
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "akiritsu@outlook.com"
github: "akiritsu/pRoJEct-NeGYa"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "@Jayasurya.Obbu"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"