## Settings
title: JayasuryaObbu
owner: "Jay"
url: "https://mr-circuit.github.io"
baseurl: "/Jayasurya-Obbu"
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "hello@jayasurya.me"
github: "mr-circuit"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "@Jayasurya.Obbu - Living in '`r format(Sys.Date(), "%Y")`'"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "αβγδεζηθικλμνξοπρστυφχψω∷∫∮∝∞∧∨∑∏∪∩∈∵∴⊥‖∠⌒⊙≌√"